// src/pages/contact.vue
<template>
  <div class="row">
    <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
      <h1>Contact <small class="text-muted">for bugs and question</small></h1>
      Please to the message via
      <a href="https://twitter.com/livejam_db" rel="noopener" target="_blank">
        <fa :icon="['fab', 'twitter']" fixed-width />Twitter
      </a>
      or
      <a href="https://github.com/jamband/plusarchive.com/issues" rel="noopener" target="_blank">
        <fa :icon="['fab', 'github']" fixed-width />GitHub
      </a>
      Issues. Thank you.
    </div>
  </div>
</template>

<script>
export default {
  head () {
    return {
      title: 'Contact'
    }
  }
}
</script>

// src/pages/contact/index.tsx
import Head from "next/head";
import { APP_DESCRIPTION, APP_REPOSITORY_URL } from "~/constants/app";
import { IconGitHub } from "~/icons/github";
import { IconTwitter } from "~/icons/twitter";
import { Layout } from "~/layouts/layout";
import type { PageComponent } from "../_app";

const Page: PageComponent = () => {
  return (
    <>
      <Head>
        <meta name="description" content={APP_DESCRIPTION} />
        <meta property="og:description" content={APP_DESCRIPTION} />
      </Head>
      <div className="lg:px-40">
        <h1>
          Contact{" "}
          <small className="text-base text-gray-400">
            for bugs and questions
          </small>
        </h1>
        <p>
          Please to the message via{" "}
          <a
            href="https://twitter.com/livejam_db"
            className="text-rose-500 underline active:text-rose-500"
            target="_blank"
            rel="noreferrer"
          >
            <IconTwitter className="mr-1 h-4 w-4 align-[-0.125em]" />
            Twitter
          </a>{" "}
          or{" "}
          <a
            href={`${APP_REPOSITORY_URL}/issues`}
            className="text-rose-500 underline active:text-rose-500"
            target="_blank"
            rel="noreferrer"
          >
            <IconGitHub className="mr-1 h-4 w-4 align-[-0.125em]" />
            GitHub
          </a>{" "}
          Issues. Thank you.
        </p>
      </div>
    </>
  );
};

Page.getLayout = (page) => <Layout title="Contact">{page}</Layout>;

export default Page;
