// src/components/TotalCount/index.vue
<template>
  <span class="text-body">{{ text() }}</span>
</template>

<script>
export default {
  name: 'TotalCount',
  props: {
    total: {
      type: Number,
      required: true
    }
  },
  methods: {
    text () {
      return this.total === 0
        ? 'No results found'
        : `${new Intl.NumberFormat('en-US').format(this.total)} results`
    }
  }
}
</script>

// src/components/total-count/index.tsx
import { Component } from "./component";
import type { Props } from "./types";

export const TotalCount: React.FC<Props> = (props) => {
  const total =
    props.total === 0
      ? "No results found"
      : `${new Intl.NumberFormat("en-US").format(props.total)} results`;

  return <Component total={total} className={props.className} />;
};
